smoothie/smoothie/urls.py
from django.contrib import admin
from django.urls import path, include
from django.urls import path
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', views.index, name='index'),
    path('index/<int:smoothie_id>/', views.index, name='index_smoothie_id'),
    path('register/', views.register, name='register'),
    path('create_smoothie/', views.create_smoothie, name='create_smoothie'),
    path('view_smoothie/<int:smoothie_id>/',
         views.view_smoothie, name='view_smoothie'),
    path('list_smoothies/', views.list_smoothies, name='list_smoothies'),
    path('mysmoothies/<int:smoothie_id>/', views.index, name='index_smoothie'),
]

smoothie/forms.py
from django import forms
import requests
from smoothie.models import Smoothie


class SearchForm(forms.Form):
    query = forms.CharField()

    def submit(self):
        query = self.cleaned_data['query']
        url = 'https://api.nal.usda.gov/fdc/v1/foods/search'
        params = {
            'api_key': 'elhyRfYJ42dSR6zWHJXgOeU9zudQ7wfawa1hYFP8',
            'query': query,
            'pageSize': 10,
        }
        response = requests.get(url, params=params)
        response.raise_for_status()
        return response.json()['foods']


class SmoothieForm(forms.ModelForm):
    class Meta:
        model = Smoothie
        fields = ['name']

smoothie/templates/create_smoothie.html
{% extends 'layout.html' %}

{% block body %}
<div class="create_smoothie_form">
  <h1>Create a Smoothie</h1>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Create</button>
  </form>
</div>
{% endblock %}

smoothie/templates/index.html
{% extends "layout.html" %} {% load nutrition_tags %}{% block body %}
<div class="index_search">
  <h1>Smoothie</h1>
  <p>Find your favorite fruits</p>
<form method="post" id="search-form" data-url="{% url 'index' %}">
  {% csrf_token %}
  <input
    type="text"
    name="query"
    placeholder="fruit search"
    id="id_query"
    class="input_size"
    required
  />
  <button type="submit">Search</button>
  {% if smoothie_id %}
  <input type="hidden" name="smoothie_id" value="{{ smoothie_id }}" />
  {% endif %}
</form>
</div>

{% if foods %}
<div id="csrf-token" style="display:none;">{% csrf_token %}</div>
<ul>
  {% for food in foods %} {% if forloop.first %}
  <div class="index_search_result" id="search-results">
    <h2><a href="#">{{ food.description }}</a></h2>
    <p class="index_info">
      <strong>Note:</strong> The nutrient values displayed below are based on a
      100g serving.
    </p>
    <p>
      Calories: {{ food.foodNutrients|get_nutrient_value_by_name:"Energy" }}
    </p>
    <p>Protein: {{ food.foodNutrients|get_nutrient_value_by_name:"Protein"}}</p>
    <p>
      Calcium: {{ food.foodNutrients|get_nutrient_value_by_name:"Calcium, Ca" }}
    </p>
    <p>Iron: {{ food.foodNutrients|get_nutrient_value_by_name:"Iron, Fe" }}</p>
    <p>Vitamin A: {{ food.foodNutrients|get_nutrient_value_by_id:"1104" }}</p>
    <p>Vitamin C: {{ food.foodNutrients|get_nutrient_value_by_id:1162 }}</p>
    <p>
      Sodium: {{ food.foodNutrients|get_nutrient_value_by_name:"Sodium, Na" }}
    </p>
    <p>Dietary Fiber: {{ food.foodNutrients|get_nutrient_value_by_id:1079 }}</p>
    <p>Total Sugars: {{ food.foodNutrients|get_nutrient_value_by_id:2000 }}</p>
    <p>
      Potassium: {{ food.foodNutrients|get_nutrient_value_by_name:"Potassium, K"}}
    </p>
    {% if smoothie_id %}
    <form
      method="post"
      action="{% url 'view_smoothie' smoothie_id=smoothie_id %}"
    >
      {% csrf_token %}
      <input type="hidden" name="fdc_id" value="{{ food.fdcId }}" />
      <input type="hidden" name="description" value="{{ food.description }}" />
      <button type="submit">Add to Smoothie</button>
    </form>
    {% endif %}
  </div>
  {% endif %} {% endfor %}
</ul>
{% endif %} {% endblock %}
{% block extra_js %}
<script>
  document.addEventListener("DOMContentLoaded", function () {
  const searchForm = document.getElementById("search-form");
  const csrfToken = document.getElementById("csrf-token").firstElementChild
    .value;
  const searchResults = document.getElementById("search-results");

  searchForm.addEventListener("submit", function (event) {
    event.preventDefault();

    const formData = new FormData(searchForm);
    formData.append("csrfmiddlewaretoken", csrfToken);
    formData.append("quantity", document.getElementById("quantity").value); // Add this line
    const searchUrl = searchForm.getAttribute("data-url");

    fetch(searchUrl, {
      method: "POST",
      body: formData,
    })
      .then((response) => response.text())
      .then((html) => {
        const parser = new DOMParser();
        const doc = parser.parseFromString(html, "text/html");
        const newSearchResults = doc.getElementById("search-results");

        if (newSearchResults) {
          searchResults.innerHTML = newSearchResults.innerHTML;
        } else {
          searchResults.innerHTML = "";
        }
      })
      .catch((error) => {
        console.error("Error fetching search results:", error);
      });
  });
});
</script>
{% endblock %}

smoothie/templates/layout.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <title>{% block title %}Smoothie App{% endblock %}</title>
    <link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Lato:ital,wght@0,100;0,300;0,400;0,700;0,900;1,100;1,300;1,400;1,700;1,900&display=swap" rel="stylesheet">

    <link href="{% static 'styles.css' %}" rel="stylesheet" />
    <script src="{% static 'main.js' %}"></script>
  </head>

  <body>
    <nav>
      <ul>
        {% if user.is_authenticated %}
        <li><a href="{% url 'index' %}">Home</a></li>
        <li><a href="{% url 'create_smoothie' %}">Create Smoothie</a></li>
        <li><a href="{% url 'list_smoothies' %}">Custom Smoothies</a></li>
        <li><a href="{% url 'logout' %}">Logout</a></li>
         <li><span>Welcome, {{ user.username }}</span></li>
        {% else %}
        <li><a href="{% url 'login' %}">Login</a></li>
        <li><a href="{% url 'register' %}">Register</a></li>
        {% endif %}
      </ul>
    </nav>
    <div class="body">{% block body %} {% endblock %}</div>
    {% block extra_js %} {% endblock %}
  </body>
</html>

smoothie/templates/list_smoothies.html
{% extends "layout.html" %}
{% load nutrition_tags %}
{% block body %}
<div class="mySmoothies">
  <h1>Custom Smoothies</h1>
  <ul>
    {% for smoothie in smoothies %}
    <li>
      <a class="smoothie_name" href="{% url 'view_smoothie' smoothie_id=smoothie.id %}">{{ smoothie.name }}</a>
      <a class="smoothie_addFruit" href="{% url 'index_smoothie_id' smoothie_id=smoothie.id %}">Add fruits to this smoothie</a>

      {% if request.user == smoothie.user %}
        <form method="post" style="display:inline;">
          {% csrf_token %}
          <input type="hidden" name="delete_smoothie_id" value="{{ smoothie.id }}">
          <button type="submit">Delete</button>
        </form>
      {% endif %}

      <form method="post" style="display:inline;">
        {% csrf_token %}
        <input type="hidden" name="rate_smoothie_id" value="{{ smoothie.id }}">
        <label class="smoothie_rating" for="rating">Rate this smoothie:</label>
        <select name="rating" id="rating">
          <option value="1">1 star</option>
          <option value="2">2 stars</option>
          <option value="3">3 stars</option>
          <option value="4">4 stars</option>
          <option value="5">5 stars</option>
        </select>
        <button type="submit">Submit</button>
      </form>
    {% with smoothie|average_rating as avg_rating %}
      {% if avg_rating != "N/A" %}
        <p class="average_rating">Average rating: {{ avg_rating }} Stars</p>
      {% endif %}
      <hr/>
    {% endwith %}
    </li>
    {% empty %}
    <li>No smoothies created yet.</li>
    {% endfor %}
  </ul>
</div>
{% endblock %}

smoothie/templates/register.html
{% extends "layout.html" %} {% block body %}
<div class="register">
  <h1>Register</h1>
  <form method="post">
    {% csrf_token %} {{ form.as_p }}
    <button type="submit">Register</button>
  </form>
</div>
{% endblock %}

smoothie/templates/view_smoothie.html
{% extends 'layout.html' %}
{% load nutrition_tags %}
{% block body %}
<div class="view_smoothie">
  <h1 style="margin: 0">{{ smoothie.name }}</h1>
  <h6>Click ingredients for more info.</h6>
  <ul>
    {% for ingredient in ingredients %}
    <li data-fdc-id="{{ ingredient.fdc_id }}" onclick="showNutrientData(event)">
      {{ ingredient.quantity }} x {{ ingredient.description }} ({{ ingredient.grams|multiply:100|floatformat:0 }} grams)
      <form method="post" style="display: inline">
        {% csrf_token %}
        <input type="hidden" name="delete_ingredient_id" value="{{ ingredient.id }}" />
        <button type="submit" style="background: none; border: none; color: blue">Delete</button>
      </form>
    </li>
    {% endfor %}
  </ul>
  <div id="ingredient-details" style="display: none"></div>
  <form method="post">
    {% csrf_token %}
    <input type="text" name="{{ form.query.name }}" placeholder="fruit search" id="{{ form.query.auto_id }}" required />
    <button class="vs_btn" type="submit">Search</button>
  </form>
  {% if foods %}
  <ul>
    {% for food in foods %}
    <div>
      <h2>{{ food.description }}</h2>
      <p><strong>Note:</strong> The nutrient values displayed below are based on a 100g serving.</p>
      <p>Calories: {{ food.foodNutrients|get_nutrient_value_by_name:"Energy" }} kcal</p>
      <p>Protein: {{ food.foodNutrients|get_nutrient_value_by_name:"Protein"}}</p>
      <p>Calcium: {{ food.foodNutrients|get_nutrient_value_by_name:"Calcium, Ca" }}</p>
      <p>Iron: {{ food.foodNutrients|get_nutrient_value_by_name:"Iron, Fe" }}</p>
      <p>Vitamin A: {{ food.foodNutrients|get_nutrient_value_by_id:"1104" }}</p>
      <p>Vitamin C: {{ food.foodNutrients|get_nutrient_value_by_id:1162 }}</p>
      <p>Sodium: {{ food.foodNutrients|get_nutrient_value_by_name:"Sodium, Na" }}</p>
      <p>Potassium: {{ food.foodNutrients|get_nutrient_value_by_name:"Potassium, K" }}</p>
      <p>Dietary Fiber: {{ food.foodNutrients|get_nutrient_value_by_id:1079 }}</p>
      <p>Total Sugars: {{ food.foodNutrients|get_nutrient_value_by_id:2000 }}</p>
      <form method="post">
        {% csrf_token %}
        <input type="hidden" name="fdc_id" value="{{ food.fdcId }}" />
        <input type="hidden" name="description" value="{{ food.description }}" />
        <label for="quantity">Quantity:</label>
        <input type="number" name="quantity" id="quantity" min="1" value="1" />
        <label for="grams">Weight (g):</label>
        <input type="number" name="grams" id="grams" min="1" value="100" step="1" />
        <button type="submit">Add to smoothie</button>
      </form>
    </div>
    {% endfor %}
  </ul>
  {% endif %}
{% if ingredients %}
<div class="nutrition_info">
  <h2>Nutritional Information</h2>
  <ul>
    <p class="index_info"><strong>Note:</strong> The nutrient values displayed below are based on a 100g serving per Fruit.</p>
    <li>Energy: {{ total_nutrients|get_total_nutrient_value_by_id:'1008'|calculate_nutrient_value:grams }} kcal</li>
    <li>Protein: {{ total_nutrients|get_total_nutrient_value_by_id:'1003'|calculate_nutrient_value:grams }} g</li>
    <li>Calcium: {{ total_nutrients|get_total_nutrient_value_by_id:'1087'|calculate_nutrient_value:grams }} mg</li>
    <li>Iron: {{ total_nutrients|get_total_nutrient_value_by_id:'1089'|calculate_nutrient_value:grams }} mg</li>
    <li>Vitamin A: {{ total_nutrients|get_total_nutrient_value_by_id:'1104'|calculate_nutrient_value:grams }} IU</li>
    <li>Vitamin C: {{ total_nutrients|get_total_nutrient_value_by_id:'1162'|calculate_nutrient_value:grams }} mg</li>
    <li>Sodium: {{ total_nutrients|get_total_nutrient_value_by_id:'1093'|calculate_nutrient_value:grams }} mg</li>
    <li>Fiber: {{ total_nutrients|get_total_nutrient_value_by_id:'1079'|calculate_nutrient_value:grams }} g</li>
    <li>Sugars: {{ total_nutrients|get_total_nutrient_value_by_id:'2000'|calculate_nutrient_value:grams }} g</li>
    <li>Potassium: {{ total_nutrients|get_total_nutrient_value_by_id:'1092'|calculate_nutrient_value:grams }} mg</li>
  </ul>
</div>
{% endif %}
</div>
  {% endblock %} {% block extra_js %}
  <script>
    function showNutrientData(event) {
      const fdcId = event.target.dataset.fdcId;
      const apiKey = "elhyRfYJ42dSR6zWHJXgOeU9zudQ7wfawa1hYFP8";
      const url = `https://api.nal.usda.gov/fdc/v1/food/${fdcId}?api_key=${apiKey}`;

      fetch(url)
        .then((response) => response.json())
        .then((data) => {
          const nutrients = data.foodNutrients;

          const details = document.getElementById("ingredient-details");
          details.innerHTML = `
                <button id="close-details" style="float: right;">Close</button>
                <h3>${data.description}</h3>
                <p><strong>Note:</strong> The nutrient values displayed below are based on a 100g serving.</p>
                <p>Calories: ${getNutrientValueByName(
                  nutrients,
                  "Energy"
                )} kcal </p>
                <p>Protein: ${getNutrientValueByName(
                  nutrients,
                  "Protein"
                )} g</p>
                <p>Calcium: ${getNutrientValueByName(
                  nutrients,
                  "Calcium"
                )} mg</p>
                <p>Iron: ${getNutrientValueByName(nutrients, "Iron, Fe")} mg</p>
                <p>Vitamin A: ${getNutrientValueById(nutrients, 1104)} IU</p>
                <p>Vitamin C: ${getNutrientValueById(nutrients, 1162)} mg</p>
                <p>Sodium: ${getNutrientValueByName(
                  nutrients,
                  "Sodium"
                )} mg</p>
                <p>Potassium: ${getNutrientValueById(nutrients, 1092)} mg</p>
                <p>Dietary Fiber: ${getNutrientValueById(nutrients, 1079)} g</p>
                <p>Total Sugars: ${getNutrientValueById(nutrients, 2000)} g</p>
            `;
          details.style.display = "block";

          /*Pop Up Close btn */
          document.getElementById('close-details').addEventListener('click', function () {
            details.style.display = "none";
          });
        })
        .catch((error) =>
          console.error("Error fetching nutrient data:", error)
        );
    }



    function getNutrientValueByName(nutrients, name) {
      const nutrient = nutrients.find((n) => n.nutrient.name === name);
      return nutrient ? nutrient.amount : "N/A";
    }

    function getNutrientValueById(nutrients, id) {
      const nutrient = nutrients.find((n) => n.nutrient.id === id);
      return nutrient ? nutrient.amount : "N/A";
    }
  </script>
{% endblock %}